### ISSUE TITLE
Document supported CNI

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/k8s-cluster-k3s-ubuntu-ansible#12]
Probably only want to stay with calico and flannel for now.

**Comment by MansM** [comment]
For flannel be careful with kube 1.7:
https://github.com/coreos/flannel/issues/1243

**Comment by onedr0p** [comment]
@MansM is there a way to provide host-gw during k3s install? Like a flag or something?

**Comment by onedr0p** [comment]
Found it! 

https://github.com/rancher/docs/pull/2241/files

**Comment by onedr0p** [comment]
@MansM I'm guessing you needed to add this to your systemd service file on your k3s master so it persisted on reboot?

**Comment by onedr0p** [comment]
I updated our config here

https://github.com/k8s-at-home/k8s-cluster/commit/9b863205e2b9abacc8cfdc179b9bf48ab4e26590

**Comment by carpenike** [comment]
Only needs to be on the master config and the clients share it?

**Comment by MansM** [comment]
On an existing cluster:
kubectl edit cm -n kube-system kube-flannel-cfg

More info on backends: 
https://github.com/coreos/flannel/blob/master/Documentation/backends.md

**Comment by onedr0p** [comment]
@carpenike only master node

https://rancher.com/docs/k3s/latest/en/installation/install-options/

**Comment by onedr0p** [comment]
@MansM in order for the setting to persist thru a reboot you need to add this option to the systemd file on the master node.

**Comment by MansM** [comment]
I have to take your word for it, not using K3s myself. Running Kubeadm build cluster at home: https://github.com/MansM/vagrant-kubeadm

Though not in vagrant but on 2x Dell r710 with a pi3 as master

**Comment by onedr0p** [comment]
Oh, thought you were using k3s, ignore me :)
