### ISSUE TITLE
Allow option for over-writing kube config

### ISSUE THREAD

**Issue by carpenike** [onedr0p/k8s-cluster-k3s-ubuntu-ansible#21]
toggle with variable, default to no

**Comment by onedr0p** [comment]
I was wondering why it was trying to connect to k3s-master-a 😆 I had to re-grab my real kubeconfig

**Comment by carpenike** [comment]
Would be cool to figure out how to append to an existing. Would probably get unwieldy though if you did a bunch of e2e tests.

**Comment by onedr0p** [comment]
No doubt, I think dumping it in the root of the project repo is good for now.
