### ISSUE TITLE
Add taint to storage nodes for rook-ceph

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/k8s-cluster-k3s-ubuntu-ansible#39]
Would be nice to taint the servers running rook-ceph and apply tolerations to the rook-ceph deployments. This way standard workloads can only be ran on the worker nodes without any affinity rules.

**Comment by onedr0p** [comment]
There's documentation on how to apply taints to each container in the deployments.

https://rook.io/docs/rook/v1.2/helm-operator.html

**Comment by carpenike** [comment]
Perhaps a `Ceph.converged: true` Variable that when false sets a taint similar to the master one?

Then use the tolerations within the helm chart to allow Ceph to run on the tainted node.

**Comment by onedr0p** [comment]
Need to apply tolerations to deployments

**Comment by onedr0p** [comment]
Also need to apply tolerations to the cluster.yaml

https://github.com/k8s-at-home/k8s-cluster/blob/master/cluster/rook-ceph/cluster/cluster.yaml
