### ISSUE TITLE
k3s on VMware vSphere

### ISSUE THREAD

**Issue by likamrat** [onedr0p/k8s-cluster-k3s-ubuntu-ansible#45]
FYI I started to work on the k3s on vSphere. I have the infra deployment kinda done using terraform. 
I think would be good to join forces here.

https://github.com/likamrat/k3s_vmware

**Comment by onedr0p** [comment]
I invited you to the org, feel free to join us on discord too.

**Comment by carpenike** [comment]
Cool. I wonder if it makes sense to rename our test folder? It has infrastructure deployment pieces in there to support testing but they could be used for deployment too?
