### ISSUE TITLE
Calico currently enabled, flannel should be configurable to use instead

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/k8s-cluster-k3s-ubuntu-ansible#5]
Related to BGP mode.

**Comment by carpenike** [comment]
[This](https://github.com/carpenike/k3s-bootstrap/blob/master/roles/k3s/master/templates/k3s.service.j2#L32) line needs an if/then statement to turn it on/off based on whether [this](https://github.com/carpenike/k3s-bootstrap/blob/master/group_vars/all.yml#L11) line is set to calico or flannel or ...

[BGP](https://github.com/carpenike/k3s-bootstrap/blob/master/roles/k3s/master/tasks/calico.yml) is already configured with a where clause for the same variable [here](https://github.com/carpenike/k3s-bootstrap/blob/master/roles/k3s/master/tasks/calico.yml#L20).

**Comment by onedr0p** [comment]
Can also do a conditional with ansible

```
- include: calico.yml
  when: k3s_master_cli is search("--flannel-backend=none")
```

This would probably remove the need for the `calico` variable in the global variables.
